### ISSUE TITLE
Another repo exists

### ISSUE THREAD

**Issue by kyungw00k** [andromedarabbit/awesome-alfred-workflows#1]
https://github.com/derimagia/awesome-alfred-workflows

**Comment by andromedarabbit** [comment]
Well, I knew that. However, I have made a decision to create my own version for two reasons:
1. I just wanted to give my friends my own recommendations, not others'.
2. I did not agree with many of workflows in the document.

I am not saying that mine is better than his. I am just saying that these two are very different projects with different taste. Hope that you love the both 😃
